name = "caldav_gleam"
version = "1.0.0"

description = "A lightweight Gleam CalDAV client library for discovery, calendars, and events."
licences = ["Apache-2.0"]
repository = { type = "github", user = "RedHelium", repo = "caldav_gleam" }
links = [{ title = "GitHub", href = "https://github.com/RedHelium/caldav_gleam" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
